pipeline:
  # unit-test:
  #   image: node:alpine
  #   commands:
  #     - yarn install
  #     - yarn test
  
  dockerhub:
    image: plugins/docker
    repo: veekungx/server
    secrets: [docker_username,docker_password]
    tags:
      - latest
      - "dev-${DRONE_COMMIT_SHA:0:8}"
    when:
      event: push
      branch: master
  
  deliver-preview:
    image: plugins/docker
    repo: veekungx/server
    secrets: [docker_username,docker_password]
    tags:
      - preview
      - "preview-${DRONE_COMMIT_SHA:0:8}"
    when:
      event: pull_request
      
  helm-deploy-preview:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    helm_repos: sunday=http://chartmuseum.easysunday.com
    chart: sunday/preview
    # wait: true
    release: repo-${DRONE_REPO_NAME}-pr-${DRONE_PULL_REQUEST}
    values: server.image.tag=preview
    secrets: [api_server, kubernetes_token]
    # namespace: ${DRONE_REPO_NAME}-${DRONE_PULL_REQUEST}
    namespace: preview
    debug: true
    when:
      event: pull_request

  post-github:
    image: plugins/webhook
    pull: true
    urls:
      - https://api.github.com/repos/veekungx/${DRONE_REPO_NAME}/issues/${DRONE_PULL_REQUEST}/comments
    username: veekungx
    secrets:
      - source: github_token
        target: webhook_password
    template: >
      {
        "body" : "Preview Available at \n http://repo-${DRONE_REPO_NAME}-pr-${DRONE_PULL_REQUEST}-preview-server.54.169.212.22.nip.io \n http://repo-${DRONE_REPO_NAME}-pr-${DRONE_PULL_REQUEST}-preview-server.54.169.212.22.nip.io"
      }
    debug: true
    when:
      event: pull_request
  

  # helm-chartmuseum:
  #   image: quay.io/honestbee/drone-chartmuseum
  #   repo_url: http://chartmuseum.easysunday.com
  #   chart_path: chart/server
  #   when:
  #     branch: master

  # helm_deploy_staging:
  #   image: quay.io/ipedrazas/drone-helm
  #   skip_tls_verify: true
  #   chart: ./charts/server
  #   release: 'thi-server'
  #   wait: true
  #   recreate_pods: true
  #   service_account: tiller
  #   secrets: [api_server, kubernetes_token]
  #   namespace: thi
  #   debug: true
  #   when:
  #     event: push
  #     branch: master

  # tagged_docker:
  #   image: plugins/docker
  #   repo: veekungx/server
  #   secrets: [docker_username,docker_password]
  #   tags:
  #     - latest
  #     - "dev-${DRONE_COMMIT_SHA}"
  #     - "${DRONE_TAG##v}"
  #   when:
  #     event: tag